Create a similarity map from a set of network or the communities in a hierarchical model

In [137]:
from math import*
import numpy as np
import pandas as pd
import ndex2
import getpass
import requests
import io
import igraph
import networkx as nx
import math

from IPython.display import display, HTML

In [2]:
# Watch out for typos and be sure to hit enter in the field to set the value!!!
NDEXUSER = getpass.getpass()

········


In [3]:
# Watch out for typos and be sure to hit enter in the field to set the value!!!
NDEXPASSWORD = getpass.getpass()

········


In [89]:
SERVER="http://www.ndexbio.org"
#This is used to create clickable links to view the networks in NDEx
NETWORK_BASE_URL = 'http://ndexbio.org/viewer/networks/'
print(NDEXUSER)
print(NDEXPASSWORD)
ndx=ndex2.Ndex2(SERVER, NDEXUSER, NDEXPASSWORD)
ndx

dexterpratt
cytoscaperules


In [144]:
#example_set_id = "d0096935-4b05-11ec-b3be-0ac135e8bacf"
example_set_id = "1e6a6016-fc81-11ea-99da-0ac135e8bacf"
def describe_network_set(set_id):
    set = ndx.get_network_set(set_id)
    display(HTML("<h2>" + set.get("name") + "</h2>"))
    display(HTML(set.get("description")))
    for network_id in set.get("networks"):
        summary = ndx.get_network_summary(network_id)
        display(HTML("<h4>" + summary.get("name") + "</h4>"))
        if summary.get("description"):
            display(HTML(summary.get("description")))
    return set

#example_set = describe_network_set(example_set_id)
example_set = ndx.get_network_set(example_set_id)
example_set

{'name': 'Signaling, Disease and Cancer Pathways',
 'description': '<p>This set contains  human pathways manually-curated from the literature by the SIGNOR Team at the University of Rome</p><p> <img src="https://signor.uniroma2.it/img/signor_logo.png" alt="Figure 1" width="200"/></p>',
 'ownerId': '0db1f2dc-103f-11e8-b939-0ac135e8bacf',
 'networks': ['02a8eede-97f1-11eb-9e72-0ac135e8bacf',
  '035163e3-97f1-11eb-9e72-0ac135e8bacf',
  '03dcfa67-1e5f-11e8-b939-0ac135e8bacf',
  '0522eea1-97f1-11eb-9e72-0ac135e8bacf',
  '077e15fd-1e5f-11e8-b939-0ac135e8bacf',
  '0934c6b0-1e5f-11e8-b939-0ac135e8bacf',
  '0ae84313-1e5f-11e8-b939-0ac135e8bacf',
  '0b6cbc27-97f1-11eb-9e72-0ac135e8bacf',
  '0ced3ad6-1e5f-11e8-b939-0ac135e8bacf',
  '0f019be9-1e5f-11e8-b939-0ac135e8bacf',
  '10f360ba-97f1-11eb-9e72-0ac135e8bacf',
  '126da4b2-97f1-11eb-9e72-0ac135e8bacf',
  '12c33ec7-97f1-11eb-9e72-0ac135e8bacf',
  '1af025eb-afe8-11e9-8bb4-0ac135e8bacf',
  '1af7be3b-1e5f-11e8-b939-0ac135e8bacf',
  '1b3873d6-8f9a-11

## Similarity Metrics
- Jacquard
- Cosine

In [145]:
# Jacquard similarity for two sets:

# The ratio of size of the intersection to the size of the union
 
def jaccard_similarity(x,y):
 
 intersection_cardinality = len(set.intersection(*[set(x), set(y)]))
 union_cardinality = len(set.union(*[set(x), set(y)]))
 return intersection_cardinality/float(union_cardinality)

# Cosine similarity for two sets:
# loop through each list, find distinct genes and map them to a
# unique number starting at zero
def make_all_genes(gene_lists):
    all_genes = {}
    i = 0
    for gene_list in gene_lists:
        for gene in gene_list:
            if gene not in all_genes:
                all_genes[gene] = i
                i += 1
    return all_genes

def cosine_similarity(list_a, list_b, all_genes):
    a = list2vec(list_a, all_genes)
    print(a)
    b = list2vec(list_b, all_genes)
    print(b)
    # use numpy's dot product to calculate the cosine similarity
    return np.dot(a, b) / np.sqrt(np.dot(a, a) * np.dot(b, b))
    
def list2vec(list, all_genes):
    # create a vector of zeros the length of all genes
    vec = np.zeros(len(all_genes))
    # for each gene in the list, get the index and set that element of the vector to 1
    for gene in list:
        index = all_genes[gene] # fragile, need to test to be sure all_genes contains gene
        vec[index] = 1
    return vec

def make_jaccard_similarity_matrix(gene_lists):
    size = len(gene_lists)
    matrix = np.zeros((size,size))
    for i in range(size):
        print(i)
        for j in range(size):
            sim = jaccard_similarity(gene_lists[i], gene_lists[j])
            matrix[i,j] = sim
    return matrix
            
def make_cosine_similarity_matrix(gene_lists):
    size = len(gene_lists)
    matrix = np.zeros((size,size))
    all_genes = make_all_genes(gene_lists)
    #for gene_list in gene_lists:
    #    vectors.append(list2vec(gene_list, all_genes))
    for i in range(size):
        for j in range(size):
            sim = cosine_similarity(gene_lists[i], gene_lists[j], all_genes)
            matrix[i,j] = sim
    return matrix
    

In [146]:
a = ['TP53', 'EGFR', 'XRCC1', "FOXO3", "TLE1"]
b = ['TP53', 'EGFR', 'XRCC1', "AKT1", "GSK3B", 'E2F1']
l = [a,b]
m = make_jaccard_similarity_matrix(l)
m

0
1


array([[1.   , 0.375],
       [0.375, 1.   ]])

In [147]:
a = ['TP53', 'EGFR', 'XRCC1', "FOXO3", "TLE1"]
b = ['TP53', 'EGFR', 'XRCC1', "AKT1", "GSK3B", 'E2F1']
l = [a,b]
m = make_cosine_similarity_matrix(l)
m

[1. 1. 1. 1. 1. 0. 0. 0.]
[1. 1. 1. 1. 1. 0. 0. 0.]
[1. 1. 1. 1. 1. 0. 0. 0.]
[1. 1. 1. 0. 0. 1. 1. 1.]
[1. 1. 1. 0. 0. 1. 1. 1.]
[1. 1. 1. 1. 1. 0. 0. 0.]
[1. 1. 1. 0. 0. 1. 1. 1.]
[1. 1. 1. 0. 0. 1. 1. 1.]


array([[1.        , 0.54772256],
       [0.54772256, 1.        ]])

## Process a Network Set
- get the set from NDEx
- for each network, extract the gene list
- make a jaccard similarity matrix from the gene list
- make a cosine similarity matrix from the gene list
- choose a similarity threshold and type for adding edges to the output network
- make the output network from the similarity matrices, set "cosine" and "jaccard" attributes on edges
- layout? Only use threshold edges?
- set the name of each nodes to be the name of the corresponding network
- set the "members" attribute of each node to the gene list
- set the style of the network to be the similarity network style
 - hide edges below threshold
- set the "network" attribute of each node to the URL to display the corresponding network in a new tab
- set the name of the network to be the name of the set
- set the derived from attribute to be the UUID of the set
- also make a link in the description point to the set
- save to NDEx

In [196]:
def get_nodes_as_df(network_id, server="www.ndexbio.org"):
    url = "".join(["https://", server, "/v3/networks/", network_id, "/export?type=node"])
    r = requests.get(url)
    df = pd.read_csv(io.StringIO(r.text),sep='\t')
    #print(df)
    return df

def get_node_name_list(network_id, server="www.ndexbio.org"):
    # TODO deal with private networks
    df = get_nodes_as_df(network_id, server=server)
    return list(df["name"])

def remove_non_genes(list_of_strings):
    return None
    
def get_gene_list(network_id):
    names = get_node_name_list(network_id)
    return names
    
def get_gene_lists_from_network_ids(network_ids):
    gene_lists = []
    for network_id in network_ids:
        gene_lists.append(get_gene_list(network_id))
    return gene_lists
        
def get_network_summaries_from_network_ids(network_ids):
    network_summaries = []
    for network_id in network_ids:
        network_summaries.append(ndx.get_network_summary(network_id))
    return network_summaries
    
def make_similarity_matrix_from_set(network_set_id, similarity_metric="jaccard"):
    network_set = ndx.get_network_set(network_set_id)
    network_ids = network_set.get("networks")  # this list establishes the order of the network ids from here on
    gene_lists = get_gene_lists_from_network_ids(network_ids)
    network_summaries = get_network_summaries_from_network_ids(network_ids)
    if similarity_metric == "jaccard":
        return make_jaccard_similarity_matrix(gene_lists), network_ids, network_summaries, gene_lists
    if simlarity_metric == "cosine":
        return make_cosine_similarity_matrix(gene_lists), network_ids, network_summaries, gene_lists
    print("unknown similarity metric" + similarity_metric)
    return None, network_ids, network_summaries, gene_lists

def make_networkx_similarity_network(similarity_matrix, threshold, network_ids, network_summaries, gene_lists):
    sim_network = nx.from_numpy_matrix(similarity_matrix > threshold)
    sim_network.remove_edges_from(nx.selfloop_edges(sim_network))
    # add the weights. from_numpy_matrix 
    for (i, j) in sim_network.edges():
        sim_network[i][j]["weight"] = similarity_matrix[i][j]
    

    attributes = {}
    for index in range(len(network_ids)):
        network_id = network_ids[index]
        network_summary = network_summaries[index]
        name = network_summary.get("name")
        description = network_summary.get("description").replace(',', " ").replace(';',' ')
        members = gene_lists[index]
        node_size = math.sqrt(len(members)) * 10
        n_members = len(members)
        attributes[index]={"label":name,
                           "description":description, 
                           "members":members, 
                           "node_size":node_size,
                           "n_members": len(members),
                           "log2members": log(len(members),2)
                          }
    nx.set_node_attributes(sim_network, attributes)
    
    return sim_network

In [197]:
jaccard, network_ids, network_summaries, gene_lists = make_similarity_matrix_from_set(example_set_id)
#print(jaccard)
#print(network_ids)
#print(network_summaries)
sim_network = make_networkx_similarity_network(jaccard, 0.2, network_ids, network_summaries, gene_lists)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50


In [176]:
nx.get_edge_attributes(sim_network, "weight")

{(0, 7): 0.15789473684210525,
 (0, 8): 0.1,
 (0, 12): 0.17857142857142858,
 (0, 13): 0.10810810810810811,
 (0, 17): 0.16981132075471697,
 (0, 18): 0.15384615384615385,
 (0, 19): 0.11764705882352941,
 (0, 20): 0.09210526315789473,
 (0, 21): 0.11290322580645161,
 (0, 22): 0.12698412698412698,
 (0, 24): 0.13114754098360656,
 (0, 30): 0.14285714285714285,
 (0, 35): 0.1044776119402985,
 (0, 37): 0.13559322033898305,
 (0, 38): 0.1044776119402985,
 (0, 43): 0.1694915254237288,
 (0, 48): 0.16,
 (0, 50): 0.14754098360655737,
 (1, 2): 0.13725490196078433,
 (1, 4): 0.0970873786407767,
 (1, 5): 0.14285714285714285,
 (1, 7): 0.09259259259259259,
 (1, 18): 0.08163265306122448,
 (1, 20): 0.08571428571428572,
 (1, 22): 0.12280701754385964,
 (1, 25): 0.14285714285714285,
 (1, 35): 0.08064516129032258,
 (1, 43): 0.12727272727272726,
 (1, 48): 0.0851063829787234,
 (1, 50): 0.10526315789473684,
 (2, 5): 0.14893617021276595,
 (2, 7): 0.14,
 (2, 8): 0.14,
 (2, 12): 0.09615384615384616,
 (2, 13): 0.106060606

In [198]:
from cyjupyter import Cytoscape
ncx=ndex2.create_nice_cx_from_networkx(sim_network)
# name the network based on the set name
ncx.set_name(example_set.get("name") + " similarity map")

TEMPLATE_UUID = 'f9bdb308-4be7-11ec-b3be-0ac135e8bacf'

# Copy the style from a template network in NDEx and apply it to our NiceCX network
ncx.apply_template(SERVER, TEMPLATE_UUID)

# Perform a layout on the networkx network and apply it to the NiceCX network
#pos = nx.drawing.layout.spiral_layout(sim_network, scale=700)
pos = nx.drawing.layout.kamada_kawai_layout(sim_network, scale=1400)

new_cart_layout = []
for node_id, coordinates in pos.items():
    new_cart_layout.append({
        'node': node_id,
        'x': coordinates[0],
        'y': -coordinates[1]   # See note below!!!
    })
ncx.set_opaque_aspect(ndex2.constants.CARTESIAN_LAYOUT_ASPECT, new_cart_layout)

cx_network = ncx.to_cx()
Cytoscape(data=cx_network, format='cx')

Generating CX


Cytoscape(data=[{'numberVerification': [{'longNumber': 281474976710655}]}, {'metaData': [{'name': 'cyVisualPro…

In [199]:


# Update existing network in NDEx and return the URL of the network's page
# as well as its UUID
network_url = ncx.upload_to(SERVER, NDEXUSER, NDEXPASSWORD)
network_uuid = network_url.split("/")[-1]


print ('=' *15)
print("Network's URL (click to view!): " + NETWORK_BASE_URL + network_uuid)
print("Network's UUID: " + network_uuid)

Generating CX
Network's URL (click to view!): http://ndexbio.org/viewer/networks/8b618fa1-4bea-11ec-b3be-0ac135e8bacf
Network's UUID: 8b618fa1-4bea-11ec-b3be-0ac135e8bacf


In [184]:
sim_network.nodes()[13]


{'label': 'Hepatocellular Tumor',
 'description': 'Hepatocellular carcinoma (HCC) is one of the most common primary malignant neoplasma of the liver  anche one of the most widespread tumors in the world with a poor prognosis. Hepatocarcinogenesis is a complex and multistep process  infact numerous signaling modules are compromised and they’re the cause of the tumor’s development and progression. Among these  the pathways that involve growth factors  such us insulin-like growth factor (IGF) or hepatocyte growth factor (HGF) are frequently found mutated in patients. Also HCC is characterized by an aberrant activation of the WNT signaling pathway. In vitro study has demonstrated that NRF2 activation preserves tumor cells from toxic exposure to reactive oxygen species and subsequent death  infact this protein promotes the expression of the anti-oxidant response genes (NQO1  HMOX1 and GSTA1). TERT promoter mutation are involved at the last step of malignant transformation  infact 90% of hum

## Process a Hierarchy
- get the hierarchy
- for each community, get the member list
- make the matrices and the network as above
- set the name of each node to be the name of the community
- set the "members" attribute of each node to be the members of the community
- ...maybe just copy ALL attributes of the hierarchy nodes
- set the style of the network to be the similarity network style
- set the derived from attribute to the UUID of the hierarchy
- make a link in the description open the hierarchy in a new tab
- ***do we prune this to avoid re-creating the parent-child links? Or is a threshold sufficient?*
- save to NDEx

In [63]:
edge_weights = nx.get_edge_attributes(sim_network, "weight")
    print(edge_weights)
    for indices, value in edge_weights.items():
        #print(indices)
        #print(value)
        weight=similarity_matrix[indices[0]][indices[1]]
        sim_network[]
        #print(weight)
        #edge_weights[indices]=weight
    print(edge_weights)
    nx.set_edge_attributes(sim_network, edge_weights)

Generating CX


Cytoscape(data=[{'numberVerification': [{'longNumber': 281474976710655}]}, {'metaData': [{'name': 'nodes', 'el…

In [167]:
cx_network


[{'numberVerification': [{'longNumber': 281474976710655}]},
 {'metaData': [{'name': 'cyVisualProperties',
    'elementCount': 3,
    'version': '1.0',
    'consistencyGroup': 1,
    'properties': []},
   {'name': 'nodes',
    'elementCount': 51,
    'idCounter': 51,
    'version': '1.0',
    'consistencyGroup': 1,
    'properties': []},
   {'name': 'edges',
    'elementCount': 322,
    'idCounter': 322,
    'version': '1.0',
    'consistencyGroup': 1,
    'properties': []},
   {'name': 'networkAttributes',
    'elementCount': 1,
    'idCounter': 1,
    'version': '1.0',
    'consistencyGroup': 1,
    'properties': []},
   {'name': 'nodeAttributes',
    'elementCount': 204,
    'idCounter': 204,
    'version': '1.0',
    'consistencyGroup': 1,
    'properties': []},
   {'name': 'edgeAttributes',
    'elementCount': 322,
    'idCounter': 322,
    'version': '1.0',
    'consistencyGroup': 1,
    'properties': []},
   {'name': 'cartesianLayout',
    'elementCount': 51,
    'idCounter': 52,

In [71]:
name_lists = []
for network_id in example_set.get("networks"):
    #print(network_id)
    name_lists.append(get_gene_list(network_id))
name_lists

[['1313',
  'ARF1',
  'ARFGAP1',
  'ASAP1',
  'CD4',
  'CLTA',
  'CLTB',
  'COPA',
  'EREG',
  'GBF1',
  'GGA3',
  'GIT1',
  'GOSR2',
  'HIV Nef',
  'KDELR1',
  'USO1',
  'YKT6',
  'ACTR2',
  'ACTR3',
  'ARHGAP10',
  'AP2A1',
  'AP2M1',
  'ARFGEF1',
  'ARFIP2',
  'CYTH1',
  'CYTH2',
  'PIP5K1A',
  'PLD2',
  'RAC1',
  'GDP',
  'GTP',
  'ATP',
  'phosphatidic acid',
  'DAG',
  'PAPOLA',
  '1-phosphatidyl-1D-myo-inositol 3,4,5-trisphosphate',
  'brefeldin A',
  'PI-4-5-P2',
  'PI-4-P',
  'choline',
  'Phosphatic acid',
  'Phosphatidylcholine'],
 ['ARF1',
  'ARF6',
  'GDP',
  'KALRN',
  'MAPK1',
  'MAPK3',
  'NME1',
  'PIP5K1A',
  'PLD1',
  'PLD2',
  'RAB11A',
  'RAB11FIP3',
  'RAC1',
  'RHOA',
  'TIAM1',
  'phosphatidic acid',
  'GM1',
  'GTP',
  'PLAUR',
  'choline',
  'Phosphatidylcholine'],
 ['ACAP1',
  'ACAP2',
  'ARF6',
  'GDP',
  'GULP1',
  'phosphate',
  'ADAP1',
  'KIF13B',
  'ADRB2',
  'ARRB1',
  'ARRB2',
  'CYTH2',
  'beta Arrestin1-2',
  'AGTR1',
  'CYTH3',
  'EGFR',
  'EGF',
 

In [52]:
name_lists = []
for network_id in example_set.get("networks"):
    #print(network_id)
    name_lists.append(get_node_name_list(network_id))
name_lists

[['1313',
  'ARF1',
  'ARFGAP1',
  'ASAP1',
  'CD4',
  'CLTA',
  'CLTB',
  'COPA',
  'EREG',
  'GBF1',
  'GGA3',
  'GIT1',
  'GOSR2',
  'HIV Nef',
  'KDELR1',
  'USO1',
  'YKT6',
  'ACTR2',
  'ACTR3',
  'ARHGAP10',
  'AP2A1',
  'AP2M1',
  'ARFGEF1',
  'ARFIP2',
  'CYTH1',
  'CYTH2',
  'PIP5K1A',
  'PLD2',
  'RAC1',
  'GDP',
  'GTP',
  'ATP',
  'phosphatidic acid',
  'DAG',
  'PAPOLA',
  '1-phosphatidyl-1D-myo-inositol 3,4,5-trisphosphate',
  'brefeldin A',
  'PI-4-5-P2',
  'PI-4-P',
  'choline',
  'Phosphatic acid',
  'Phosphatidylcholine'],
 ['ARF1',
  'ARF6',
  'GDP',
  'KALRN',
  'MAPK1',
  'MAPK3',
  'NME1',
  'PIP5K1A',
  'PLD1',
  'PLD2',
  'RAB11A',
  'RAB11FIP3',
  'RAC1',
  'RHOA',
  'TIAM1',
  'phosphatidic acid',
  'GM1',
  'GTP',
  'PLAUR',
  'choline',
  'Phosphatidylcholine'],
 ['ACAP1',
  'ACAP2',
  'ARF6',
  'GDP',
  'GULP1',
  'phosphate',
  'ADAP1',
  'KIF13B',
  'ADRB2',
  'ARRB1',
  'ARRB2',
  'CYTH2',
  'beta Arrestin1-2',
  'AGTR1',
  'CYTH3',
  'EGFR',
  'EGF',
 